spring.application.name=taskmanager
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/taskdb}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:SEU_USUARIO_REAL_AQUI}
spring.datasource.password=${DATABASE_PASSWORD:SUA_SENHA_LOCAL_AQUI}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:minhaChaveSecretaSuperSeguraParaAssinarTokensJWT123456789}
jwt.expiration=86400000